bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('remove/<int:item_id>/', views.remove_item, name='remove_item'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path(
        'checkout_success/<order_number>',
        views.checkout_success,
        name='checkout_success'
    ),
    path(
        'cache_checkout_data/',
        views.cache_checkout_data,
        name='cache_checkout_data'
    ),
    path('wh/', webhook, name='webhook'),
]

southville_sporting_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-dashboard/', include('admin_dashboard.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders'
    )
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = models.CharField(max_length=40, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        default=0
    )
    order_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0
    )
    grand_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0
    )
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default=''
    )

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = sum(
            item.lineitem_total for item in self.lineitems.all()
        )
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems'
    )
    product = models.ForeignKey(
        Product,
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    product_size = models.CharField(max_length=20, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False,
        blank=False,
        editable=False
    )

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

checkout/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('full_name', 'email', 'phone_number',
                  'street_address1', 'street_address2',
                  'town_or_city', 'postcode', 'country',
                  'county',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'country': 'Country',
            'postcode': 'Postal Code',
            'town_or_city': 'Town or City',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2',
            'county': 'County',
        }

        self.fields['full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if self.fields[field].required:
                placeholder = f'{placeholders[field]} *'
                self.fields[field].required = True
            else:
                placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            self.fields[field].label = False

checkout/views.py
from django.shortcuts import (
    render,
    redirect,
    reverse,
    get_object_or_404,
    HttpResponse
)
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings
from .forms import OrderForm
from .models import Order, OrderLineItem
from decimal import Decimal

from products.models import Product
from profiles.models import UserProfile
from profiles.forms import UserProfileForm
from bag.contexts import bag_contents

import stripe
import json


@require_POST
def cache_checkout_data(request):
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'bag': json.dumps(request.session.get('bag', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(
            request,
            'Sorry, your payment cannot be processed'
            'right now. Please try again later.'
        )
        return HttpResponse(content=e, status=400)


def checkout(request):
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY
    bag = request.session.get('bag', {})

    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            # Empty string to gather form data
            form_data = {}

            # Don't save it to the database yet
            order = order_form.save(commit=False)

            # Calculate the delivery cost
            delivery_cost = Decimal(request.POST.get('delivery_cost', '0.00'))

            # Set the delivery cost on the order
            order.delivery_cost = delivery_cost

            order.save()  # Now, save the order to the database

            grand_total = Decimal(request.POST.get('grand_total', '0.00'))

            # Store the bag items as line items in the order
            for item_key, quantity in request.session.get('bag', {}).items():
                product_id, selected_size = item_key.split('_')
                try:
                    product = Product.objects.get(pk=product_id)
                    subtotal = product.price * quantity
                    # OrderLineItem instance and append it to the order
                    OrderLineItem.objects.create(
                        order=order,
                        product=product,
                        quantity=quantity,
                        lineitem_total=subtotal,
                        product_size=selected_size,
                    )
                    # Decrement item quantity in the bag
                    if product_id in request.session['bag']:
                        request.session['bag'][product_id] -= quantity
                        if request.session['bag'][product_id] <= 0:
                            del request.session['bag'][product_id]
                except Product.DoesNotExist:
                    messages.error(request, "Product not found")

            return redirect(
                reverse(
                    'checkout_success',
                    args=[order.order_number]
                )
            )
        else:
            messages.error(request, 'There was an error with your form. \
                Please double-check your information.')
    elif not bag:
        messages.error(request, "There's nothing in your bag at the moment")
        return redirect(reverse('products'))

    current_bag = bag_contents(request)
    total = current_bag['grand_total']
    stripe_total = round(total * 100)
    stripe.api_key = stripe_secret_key

    # Only create the 'intent' if you are in the correct code path
    intent = stripe.PaymentIntent.create(
        amount=stripe_total,
        currency=settings.STRIPE_CURRENCY,
    )

    # Attempt to prefill the form with any info the
    # user maintains in their profile
    if request.user.is_authenticated:
        try:
            profile = UserProfile.objects.get(user=request.user)
            order_form = OrderForm(initial={
                'full_name': profile.user.get_full_name(),
                'email': profile.user.email,
                'phone_number': profile.default_phone_number,
                'country': profile.default_country,
                'postcode': profile.default_postcode,
                'town_or_city': profile.default_town_or_city,
                'street_address1': profile.default_street_address1,
                'street_address2': profile.default_street_address2,
                'county': profile.default_county,
            })
        except UserProfile.DoesNotExist:
            order_form = OrderForm()
    else:
        order_form = OrderForm()

    # Check if the bag is empty and do not display the form
    if not bag:
        messages.error(request, "There's nothing in your bag at the moment")
        return redirect(reverse('products'))

    if not stripe_public_key:
        messages.warning(request, 'Stripe public key is missing. \
            Did you forget to set it in your environment?')

    template = 'checkout/checkout.html'
    context = {
        'order_form': order_form,
        'stripe_public_key': stripe_public_key,
        'client_secret': intent.client_secret if intent else '',
    }

    return render(request, template, context)


def checkout_success(request, order_number):
    """
    Handle successful checkouts
    """
    save_info = request.session.get('save_info')
    order = get_object_or_404(Order, order_number=order_number)

    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
        # Attach the user's profile to the order
        order.user_profile = profile
        order.save()

        # Save the user's info
        if save_info:
            profile_data = {
                'default_phone_number': order.phone_number,
                'default_country': order.country,
                'default_postcode': order.postcode,
                'default_town_or_city': order.town_or_city,
                'default_street_address1': order.street_address1,
                'default_street_address2': order.street_address2,
                'default_county': order.county,
            }
            user_profile_form = UserProfileForm(profile_data, instance=profile)
            if user_profile_form.is_valid():
                user_profile_form.save()

    # Iterate through the order line items and update the product quantities
    for line_item in order.lineitems.all():
        product = line_item.product
        product_size = line_item.product_size
        quantity = line_item.quantity

        # Update the product size quantity in your database
        if product_size in product.size_quantity:
            product.size_quantity[product_size] -= quantity
            product.save()

    messages.success(request, f'Order successfully processed! \
        Your order number is {order_number}.')

    if 'bag' in request.session:
        del request.session['bag']

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
    }

    return render(request, template, context)

checkout/templates/checkout/checkout.html
{% extends "base.html" %}
{% load static %}
{% load subtotal_filters %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block extra_title %} | Checkout{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12">
            <h3 class="logo-font">CHECKOUT</h3>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12 l6">
            <p class="text-muted">Please fill out the form below to complete your order</p>
            <form action="{% url 'checkout' %}" method="POST" id="payment-form">
                {% csrf_token %}
                <fieldset class="checkout-form">
                    <legend class="fieldset-label text-black px-2 w-auto">BILLING INFORMATION</legend>
                    <div class="input-field checkout">
                        {{ order_form.full_name }}
                        <label for="{{ order_form.full_name.id_for_label }}">Full Name</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.email }}
                        <label for="{{ order_form.email.id_for_label }}">Email</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.phone_number }}
                        <label for="{{ order_form.phone_number.id_for_label }}">Phone Number</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.street_address1 }}
                        <label for="{{ order_form.street_address1.id_for_label }}">Street Address 1</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.street_address2 }}
                        <label for="{{ order_form.street_address2.id_for_label }}">Street Address 2</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.town_or_city }}
                        <label for="{{ order_form.town_or_city.id_for_label }}">Town or City</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.county }}
                        <label for="{{ order_form.county.id_for_label }}">County</label>
                    </div>
                    <div class="input-field checkout">
                        <input type="text" name="country" id="id_country" value="UK" readonly>
                        <label for="id_country">Country</label>
                    </div>
                    <div class="input-field checkout">
                        {{ order_form.postcode }}
                        <label for="{{ order_form.postcode.id_for_label }}">Postcode</label>
                    </div>
                    <div class="input-field checkout" id="delivery-type">
                        <p>Choose Delivery Type:</p>
                        <p>
                            <label>
                                <input name="delivery_type" type="radio" value="standard" checked />
                                <span>Standard Delivery (£{{ delivery_cost|floatformat:2 }})</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input name="delivery_type" type="radio" value="first_class" />
                                <span>1st Class Delivery (£{{ first_class_delivery_cost|floatformat:2 }})</span>
                            </label>
                        </p>
                    </div>
                    <input type="hidden" name="delivery_cost" id="delivery-cost" value="4.99">
                    <input type="hidden" name="grand_total" id="grand-total-input" value="{{ grand_total }}">
                </fieldset>
                <fieldset class="px-3">
                    <legend class="fieldset-label small text-black px-2 w-auto">Payment</legend>
                    <!-- A Stripe card element will go here -->
                    <div class="mb-3" id="card-element"></div>
                    <!-- Used to display form errors -->
                    <div class="mb-3 text-danger" id="card-errors" role="alert"></div>
                    <!-- Pass the client secret to the view so we can get the payment intent id -->
                    <input type="hidden" value="{{ client_secret }}" name="client_secret">
                </fieldset>
                <div class="submit-button text-right">
                    <div class="button-container">
                        <a href="{% url 'products' %}" class="waves-effect waves-light grey darken-3 btn">
                            <i class="material-icons left">arrow_back</i>
                            <span class="font-weight-bold">Keep Shopping</span>
                        </a>
                    </div>
                    <div class="button-container complete">
                        <!-- A Stripe button will go here -->
                        <button type="submit" id="submit-button" class="waves-effect waves-light grey darken-3 btn">
                            <span class="font-weight-bold">Pay Now</span>
                            <i class="material-icons right">lock</i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col s12 m12 l6">
            <p class="text-muted">Order Summary ({{ product_count }})</p>
            <ul class="collection">
                {% for item in bag_items %}
                <li class="collection-item">
                    <div class="item-content">
                        {% if item.product.image %}
                        <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}"
                            class="responsive-img checkout">
                        {% else %}
                        <img src="{{ MEDIA_URL }}no-image.webp" alt="No Image" class="responsive-img checkout">
                        {% endif %}
                        <div class="item-details">
                            <span class="title">{{ item.product.name }}</span>
                            <p>Size: {{ item.size|default:"N/A"|upper }}</p>
                            <p>Qty: {{ item.quantity }}</p>
                            <span class="secondary-content">
                                £{{ item.product.price | calc_subtotal:item.quantity }}</span>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <hr class="my-0">
            <ul class="collection">
                <li class="collection-item total">
                    <span class="text-black">Order Total:</span>
                    <span id="order-total" class="secondary-content">
                        {% if total == 0 %}
                        00.00
                        {% else %}
                        {{ total | floatformat:2 }}
                        {% endif %}
                        GBP
                    </span>
                </li>
                <li class="collection-item total">
                    <span class="text-black">Delivery</span>
                    <span class="secondary-content" id="hidden-delivery-cost"></span>
                </li>
                <li class="collection-item total">
                    <span class="text-black">Grand Total</span>
                    <span id="grand-total" class="secondary-content">
                        {% if grand_total == 0 %}
                        00.00
                        {% else %}
                        {{ grand_total | floatformat:2 }}
                        {% endif %}
                        GBP
                    </span>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{{ stripe_public_key|json_script:"id_stripe_public_key" }}
{{ client_secret|json_script:"id_client_secret" }}
<script src="{% static 'checkout/js/checkout.js' %}"></script>
<script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
{% endblock %}

checkout/templates/checkout/checkout_success.html
{% extends "base.html" %}
{% load static %}
{% load subtotal_filters %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block extra_title %} | Checkout Success{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12">
            <h4 class="logo-font mb-4">ORDER COMPLETE</h4>
            <p>Your order has been successfully placed.</p>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12 l4">
            <!-- Delivery address and order number -->
            <h5>ORDER INFO</h5>
            <p>ORDER NUMBER: #{{ order.order_number }}</p>
            <h5>SHIPPING ADDRESS</h5>
            <p>NAME: {{ order.full_name }}</p>
            <p>ADDRESS LINE 1: {{ order.street_address1 }}</p>
            <p>ADDRESS LINE 2: {{ order.street_address2 }}</p>
            <p>CITY: {{ order.town_or_city }}</p>
            <p>COUNTY: {{ order.county }}</p>
            <p>COUNTRY: United Kingdom</p>
            <p>POSTCODE: {{ order.postcode }}</p>
        </div>
        <div class="col s12 m12 l8">
            <!-- Order summary table without pictures -->
            <h5>ORDER SUMMARY</h5>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Size</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for line_item in order.lineitems.all %}
                    <tr>
                        <td>{{ line_item.product.name }}</td>
                        <td>{{ line_item.product_size }}</td>
                        <td>{{ line_item.quantity }}</td>
                        <td>£{{ line_item.lineitem_total }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr class="my-0">
            <ul class="collection">
                <li class="collection-item total">
                    <span class="text-black">Order Total:</span>
                    <span id="order-total" class="secondary-content">£{{ order.order_total }}</span>
                </li>
                <li class="collection-item total">
                    <span class="text-black">Delivery:</span>
                    <span class="secondary-content">£{{ order.delivery_cost|floatformat:2 }}</span>
                </li>
                <li class="collection-item total">
                    <span class="text-black">Grand Total:</span>
                    <span id="grand-total" class="secondary-content">£{{ order.grand_total|floatformat:2 }}</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col sm12">
            <div class="submit-button text-right">
                <div class="button-container">
                    {% if from_profile %}
                    <a href="{% url 'profile' %}" class="waves-effect waves-light grey darken-3 btn">
                        <i class="material-icons left">arrow_back</i>
                        <span class="font-weight-bold">Back to Profile</span>
                    </a>
                    {% else %}
                    <a href="{% url 'products' %}" class="waves-effect waves-light grey darken-3 btn">
                        <i class="material-icons left">arrow_back</i>
                        <span class="font-weight-bold">Keep Shopping</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}