bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('remove/<int:item_id>/', views.remove_item, name='remove_item'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.product_list, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path(
        'delete/<int:product_id>/',
        views.delete_product,
        name='delete_product'
    ),
    path('nothing-found/', views.nothing_found, name='nothing_found'),
]

southville_sporting_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-dashboard/', include('admin_dashboard.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=100, unique=True)
    friendly_name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.friendly_name


class Product(models.Model):
    sku = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=255)
    color = models.CharField(max_length=255, default='N/A')
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sizes = models.CharField(max_length=50, blank=True)
    size_quantity = models.JSONField(default=dict)
    image = models.ImageField(
        upload_to='product_images/',
        blank=True,
        null=True
    )
    category = models.ManyToManyField(Category)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_sizes_list(self):
        return [size.strip() for size in self.sizes.split(',') if size.strip()]

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'


def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    categories = Category.objects.all()
    friendly_names = [(c.id, c.friendly_name) for c in categories]

    self.fields['category'].choices = friendly_names
    for field_name, field in self.fields.items():  # Add parentheses to 'items'
        field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from django.urls import reverse

from .models import Product, Category
from .forms import ProductForm

synonyms = {
    "hoody": "hoodie",
    "joggers": "sweatpants",
    "jogger": "sweatpants",
    "tshirt": "t-shirt",

}


def preprocess_query(query):
    query = query.lower()
    # Check if the query is in the synonyms dictionary
    if query in synonyms:
        return synonyms[query]
    return query


def product_list(request):
    # Retrieve all products from the database
    products = Product.objects.all()
    query = request.GET.get('q')
    sort = request.GET.get('sort', 'name')
    category = request.GET.get('category', 'all')
    direction = request.GET.get('direction', 'asc')

    if sort == 'name':
        sortkey = 'lower_name'
        products = products.annotate(lower_name=Lower('name'))
    else:
        sortkey = sort

    if direction == 'desc':
        sortkey = f'-{sortkey}'

    if query:
        # Remove leading and trailing spaces from the query
        query = preprocess_query(query.strip().lower())
        queries = Q(name__icontains=query) | Q(description__icontains=query)

        # Check if the query contains a space and split it into words
        if ' ' in query:
            query_parts = query.split(' ')
            for part in query_parts:
                queries |= Q(color__icontains=part.strip())
        else:
            queries |= Q(color__icontains=query)

        products = products.filter(queries)

    if category != 'all':
        products = products.filter(category__name=category)

    products = products.order_by(sortkey)
    current_sorting = f'{sort}_{direction}'
    categories = Category.objects.all()

    if products.exists():
        context = {
            'products': products,
            'title': 'Product List',
            'search_term': query,
            'current_sorting': current_sorting,
            'categories': categories,
            'selected_category': category,
        }
        return render(request, 'products/products.html', context)
    else:
        # Redirect to the "nothing found" view when no results are found
        return redirect('nothing_found')


def product_detail(request, product_id):
    # Retrieve the product with the specified ID or
    # return a 404 error if not found
    product = get_object_or_404(Product, pk=product_id)

    context = {'product': product, 'title': 'Product Detail'}
    return render(request, 'products/product_detail.html', context)


def nothing_found(request):
    return render(request, 'products/nothing_found.html')


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            # Retrieve the selected sizes
            selected_sizes = request.POST.getlist('size')
            sizes_csv = ', '.join(selected_sizes)

            # Create and save the product instance with the sizes
            product = form.save(commit=False)
            product.sizes = sizes_csv
            product.save()

            # Save selected categories
            selected_categories = request.POST.getlist('category')
            product.category.clear()  # Clear existing categories
            for category_id in selected_categories:
                category = Category.objects.get(pk=category_id)
                product.category.add(category)
            product.save()

            messages.success(request, 'Successfully added product!')

            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add the product. Please ensure the form is valid.'
            )
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    # Retrieve the product information
    product = get_object_or_404(Product, pk=product_id)

    # Retrieve the selected category IDs for the product
    selected_category_ids = product.category.all().values_list('id', flat=True)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            selected_sizes = request.POST.getlist('size')
            product.sizes = ', '.join(selected_sizes)
            form.save()
            messages.success(request, 'Successfully updated product!')

            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid.'
            )
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
        'size_quantity': product.size_quantity,
        'selected_category_ids': selected_category_ids,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    try:
        product = get_object_or_404(Product, pk=product_id)
        product.delete()
        messages.success(request, 'Product deleted!')
    except Product.DoesNotExist:
        messages.error(request, 'Product not found.')
    except Exception as e:
        messages.error(request, f'Error deleting product: {e}')

    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link href="{% static 'products/css/products.css' %}" type="text/css" rel="stylesheet" media="screen">
{% endblock %}

{% block extra_title %} | Add Product{% endblock %}

{% block content %}
<section class="section no-pad-bot" id="index-banner">
    <div class="container">
        <div class="row center-align">
            <div class="col s12">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <form method="post" action="{% url 'add_product' %}" class="form col s12" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <label for="id_sku" class="active">Sku:</label>
                        <input type="text" placeholder="SSC00XXX" name="sku" maxlength="50" required="" id="id_sku">
                    </div>
                    <div>
                        <label for="id_name" class="active">Name:</label>
                        <input type="text" placeholder="Name" name="name" maxlength="255" required="" id="id_name">
                    </div>
                    <div>
                        <label for="id_color" class="active">Color:</label>
                        <input type="text" name="color" value="N/A" maxlength="255" required="" id="id_color">
                    </div>
                    <div>
                        <label for="id_description" class="active">Description:</label>
                        <textarea name="description" cols="40" rows="10" id="id_description"></textarea>
                    </div>
                    <div>
                        <label for="id_price" class="active">Price:</label>
                        <input type="number" name="price" step="0.01" required="" id="id_price">
                    </div>
                    <div>
                        <label for="id_sizes" class="active">Sizes:</label>
                        <input type="checkbox" name="sizes" value="" id="id_sizes">
                    </div>
                    <div>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="Small" id="size-small">
                                <span>Small</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="Medium" id="size-medium">
                                <span>Medium</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="Large" id="size-large">
                                <span>Large</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="XL" id="size-xl">
                                <span>XL</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="XXL" id="size-xxl">
                                <span>XXL</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="One Size" id="one-size">
                                <span>One Size</span>
                            </label>
                        </p>
                    </div>
                    <div>
                        <label for="id_size_quantity">Size quantity:</label>
                        <input name="size_quantity" value="{}" id="id_size_quantity">
                    </div>
                    <div id="quantity-container"></div>
                    <div>
                        <label for="id_image" class="active">Image:</label>
                        <input type="file" name="image" accept="image/*" id="id_image">
                    </div>
                    <div>
                        <label for="id_category" class="active">Category:</label>
                        <select name="category" required id="id_category" multiple>
                            <option value="1">T-Shirts</option>
                            <option value="2">Hoodies</option>
                            <option value="3">Sweatpants</option>
                            <option value="4">All Products</option>
                            <option value="5">Tracksuits</option>
                        </select>
                        <div class="help" id="id_category_helptext">
                            <div>Hold down “Control”, or “Command” on a Mac, to select more than one.</div>
                        </div>
                    </div>
                    <div class="col s12 right-align">
                        <a class="btn grey darken-3" href="{% url 'products' %}">Cancel</a>
                        <button class="btn black" type="submit">Add Product</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% block postloadjs %}
<script src="{% static 'products/js/products.js' %}"></script>
<script src="{% static 'products/js/product_owner.js' %}"></script>
{% endblock %}
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link href="{% static 'products/css/products.css' %}" type="text/css" rel="stylesheet" media="screen">
{% endblock %}

{% block extra_title %} | Edit Product{% endblock %}

{% block content %}
<section class="section no-pad-bot" id="index-banner">
    <div class="container">
        <div class="row center-align">
            <div class="col s12">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <form method="post" action="{% url 'edit_product' product_id=product.id %}" class="form col s12"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <label for="id_sku" class="active">Sku:</label>
                        <input type="text" placeholder="SSC00XXX" name="sku" maxlength="50" required="" id="id_sku"
                            value="{{ product.sku }}">
                    </div>
                    <div>
                        <label for="id_name" class="active">Name:</label>
                        <input type="text" placeholder="Name" name="name" maxlength="255" required="" id="id_name"
                            value="{{ product.name }}">
                    </div>
                    <div>
                        <label for="id_color" class="active">Color:</label>
                        <input type="text" name="color" maxlength="255" required="" id="id_color"
                            value="{{ product.color }}">
                    </div>
                    <div>
                        <label for="id_description" class="active">Description:</label>
                        <textarea name="description" cols="40" rows="10"
                            id="id_description">{{ product.description }}</textarea>
                    </div>
                    <div>
                        <label for="id_price" class="active">Price:</label>
                        <input type="number" name="price" step="0.01" required="" id="id_price"
                            value="{{ product.price }}">
                    </div>
                    <div>
                        <label for="id_sizes" class="active">Sizes:</label>
                        <input name="sizes" value="{% if product.sizes %}{{ product.sizes }}{% endif %}"
                            id="id_sizes">
                    </div>
                    <div>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="Small" id="size-small" 
                                {% if 'Small' in product.sizes %}checked{% endif %}>
                                <span>Small</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="Medium" id="size-medium" 
                                {% if 'Medium' in product.sizes %}checked{% endif %}>
                                <span>Medium</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="Large" id="size-large" 
                                {% if 'Large' in product.sizes %}checked{% endif %}>
                                <span>Large</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="XL" id="size-xl" {% if 'XL' in product.sizes and product.size_quantity.XL > 0 %}checked{% endif %}>
                                <span>XL</span>
                            </label>
                        </p>
                                               
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="XXL" id="size-xxl"
                                {% if 'XXL' in product.sizes %}checked{% endif %}>
                                <span>XXL</span>
                            </label>
                        </p>
                        <p>
                            <label>
                                <input type="checkbox" name="size" value="One Size" id="one-size"
                                {% if 'One Size' in product.sizes %}checked{% endif %}>
                                <span>One Size</span>
                            </label>
                        </p>
                    </div>
                    <div>
                        <label for="id_size_quantity" class="active">Size quantity:</label>
                        <input name="size_quantity" value="" id="id_size_quantity">
                    </div>
                    <div id="quantity-container">
                        {% for size, quantity in size_quantity.items %}
                        {% if quantity > 0 %}
                        <div class="size-container">
                            <label>{{ size }}</label>
                            <input type="number" name="size-quantity-{{ size }}" placeholder="Enter quantity" max="999"
                                value="{{ quantity }}">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div>
                        <label for="id_image" class="active">Image:</label><br>
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% get_media_prefix %}no-image.webp{% endif %}"
                             alt="{{ product.name }}" class="edit-image">
                         <br>
                         <p>Image URL:
                             <a href="{% if product.image %}{{ product.image.url }}{% else %}{% get_media_prefix %}no-image.webp{% endif %}"
                                target="_blank">{% if product.image %}{{ product.image.url }}{% else %}{% get_media_prefix%}
                                no-image.webp{% endif %}</a>
                        </p>
                        <input type="file" name="image" accept="image/*" id="id_image">
                    </div>
                    <div>
                        <label for="id_category" class="active">Category:</label>
                        <select name="category" required id="id_category" multiple>
                            <option value="1" {% if 1 in selected_category_ids %}selected{% endif %}>T-Shirts</option>
                            <option value="2" {% if 2 in selected_category_ids %}selected{% endif %}>Hoodies</option>
                            <option value="3" {% if 3 in selected_category_ids %}selected{% endif %}>Sweatpants</option>
                            <option value="4" {% if 4 in selected_category_ids %}selected{% endif %}>All Products</option>
                            <option value="6" {% if 6 in selected_category_ids %}selected{% endif %}>New</option>
                        </select>
                    </div>
                    <div class="help" id="id_category_helptext">
                        <div>Hold down “Control”, or “Command” on a Mac, to select more than one.</div>
                    </div>
                    <div class="col s12 right-align">
                        <a class="btn grey darken-3" href="{% url 'products' %}">Cancel</a>
                        <button class="btn black" type="submit">Update Product</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% block postloadjs %}
<script src="{% static 'products/js/products.js' %}"></script>
<script src="{% static 'products/js/product_owner.js' %}"></script>
{% endblock %}
{% endblock %}

products/templates/products/nothing_found.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link href="{% static 'products/css/products.css' %}" type="text/css" rel="stylesheet" media="screen">
{% endblock %}

{% block extra_js %}
<script src="{% static 'products/js/products.js' %}"></script>
{% endblock %}

{% block extra_title %} | Nothing Found{% endblock %}

{% block content %}
<main class="section no-pad-bot nothing-found" id="index-banner">
    <div class="container">
        <div class="row center-align">
            <div class="col center-align">
                {% if selected_category == 'new' %}
                <span class="card-title-new">RUN WITH NATURE</span>
                <p class="new-info">INSPIRED BY NATURE AND RUNNING OUTDOORS, HEAVYWEIGHT AND LONG LASTING FABRICS MADE
                    FOR LONGEVITY AND DISTANCE.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="section no-pad-bot hero-image" id="index-banner-1">
        <div class="container nothing-found">
            <h5 class="center-align">0 Products</h5>
            <hr class="custom-line">
            <p>No products match your search criteria.</p>
        </div>
    </div>
</main>
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link href="{% static 'products/css/products.css' %}" type="text/css" rel="stylesheet" media="screen">
{% endblock %}

{% block extra_js %}
<script src="{% static 'products/js/products.js' %}"></script>
{% endblock %}

{% block extra_title %} | Products{% endblock %}

{% block content %}
<main>
    <section class="section no-pad-bot" id="index-banner">
        <h2 class="visually-hidden">New Products</h2>
        <div class="container">
            <div class="row center-align">
                <div class="col center-align">
                    {% if selected_category == 'new' %}
                    <!-- Display information for new products -->
                    <h5 class="card-title-new">RUN WITH NATURE</h5>
                    <p class="new-info">INSPIRED BY NATURE AND RUNNING OUTDOORS, HEAVYWEIGHT AND LONG LASTING FABRICS
                        MADE
                        FOR LONGEVITY AND DISTANCE.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col l6 all-products-main">
                    <!-- Display total product count if search, categories, or sorting applied -->
                    {% if search_term or categories or current_sorting != 'None_None' %}
                    <span class="small"><a class="all-products" href="{% url 'products' %}">All Products</a> |
                        Total: {{ products|length }}</span>
                    {% endif %}
                </div>
                <div class="col l6 right-align sort-dropdown">
                    <ul>
                        <li class="sort-dropdown-trigger black-text" data-target="dropdown-filter">SORT
                            <i class="fa-solid fa-chevron-down" style="color: #000000;"></i>
                        </li>
                        <li>
                            <ul id="dropdown-filter" class="dropdown-content">
                                <!-- Sorting options for product list -->
                                <li>
                                    <!-- Sort products high to low -->
                                    <a
                                        href="?sort=price&direction=desc{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if selected_category %}&category={{ selected_category }}{% endif %}">
                                        Price, High to Low
                                    </a>
                                </li>
                                <li>
                                    <!-- Sort products low to high -->
                                    <a
                                        href="?sort=price&direction=asc{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if selected_category %}&category={{ selected_category }}{% endif %}">
                                        Price, Low to High
                                    </a>
                                </li>
                                <li>
                                    <!-- Sort products alpabetically A-Z -->
                                    <a
                                        href="?sort=name&direction=asc{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if selected_category %}&category={{ selected_category }}{% endif %}">
                                        Alphabetically, A-Z
                                    </a>
                                </li>
                                <li>
                                    <!-- Sort products alpabetically Z-A -->
                                    <a
                                        href="?sort=name&direction=desc{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if selected_category %}&category={{ selected_category }}{% endif %}">
                                        Alphabetically, Z-A
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="container">
        <h2 class="visually-hidden">Products</h2>
        <div class="row">
            {% for product in products %}
            <div class="col s6 m6 l3 card no-shadow">
                <div class="card-image products">
                    <a href="{% url 'product_detail' product.id %}">
                        <!-- Link to individual product detail page -->
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{{ MEDIA_URL }}no-image.webp{% endif %}"
                            alt="{{ product.name }}" class="zoom-image">
                    </a>
                </div>
                <div class="card-content">
                    <!-- Display product name, color and price -->
                    <span class="card-title">{{ product.name }}</span>
                    <span class="color-title">{{ product.color }}</span>
                    <span class="price">£{{ product.price }}</span>
                    <div class="card-action">
                        {% if request.user.is_superuser %}
                        <span class="product-edit">
                            <a href="{% url 'edit_product' product.id %}" class="teal-text text-darken-1">Edit</a> |
                            <a class="red-text text-accent-4 btn transparent z-depth-0 modal-trigger"
                                href="#deleteModal{{ product.id }}">Delete</a>
                        </span>
                        <!-- Modal Structure Delete Button -->
                        <div id="deleteModal{{ product.id }}" class="modal">
                            <div class="modal-content">
                                <h4>Delete Product</h4>
                                <p>Are you sure you want to delete {{ product.name }} (Product ID: {{ product.id }})?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <a href="#!" class="modal-close waves-effect btn-flat">Cancel</a>
                                <a href="{% url 'delete_product' product.id %}"
                                    class="waves-effect waves-red btn-flat">Delete</a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}